// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGmzD_fdZJ5K8M2uFcMHD301tBc6ljoNE',
    appId: '1:980332186200:android:32b35bb053947f3b81d82d',
    messagingSenderId: '980332186200',
    projectId: 'letter-26c71',
    databaseURL: 'https://letter-26c71-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'letter-26c71.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmXGFQjrg5Y0fZFsmVveZmOsuFT2x0-fc',
    appId: '1:980332186200:web:ddc598d1cf6934d981d82d',
    messagingSenderId: '980332186200',
    projectId: 'letter-26c71',
    authDomain: 'letter-26c71.firebaseapp.com',
    databaseURL: 'https://letter-26c71-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'letter-26c71.firebasestorage.app',
    measurementId: 'G-5GD8BCHX37',
  );
}
